SELECT P.PRODUCT_ID AS PRODUCT_ID
     , P.PRODUCT_NAME AS PRODUCT_NAME
     , SUM(P.PRICE * O.AMOUNT) AS SALES
FROM FOOD_PRODUCT AS P
    INNER JOIN FOOD_ORDER AS O ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE O.PRODUCE_DATE BETWEEN '2022-05-01 00:00:00' AND '2022-05-31 23:59:59'
GROUP BY PRODUCT_ID
ORDER BY SALES DESC
       , PRODUCT_ID